import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MobileNav from "../components/MobileNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-dvh relative text-primary  cursor-crosshair">
          <video
            className="fixed top-0 left-0 w-full h-full opacity-100  object-cover"
            autoPlay
            muted
            loop
            playsInline
          >
            <source src="../videos/r-video-01-1.mp4" type="video/mp4" />
            Your browser does not support the video tag.
          </video>
          <MobileNav />

          {children}
        </div>
      </body>
    </html>
  );
}
