import type { Metadata } from "next";
import "./globals.css";
import MobileNav from "../components/MobileNav";
import { ThemeProvider } from "../contexts/ThemeContext";
import ThemeVideo from "../components/ThemeVideo";

import { Plus_Jakarta_Sans, Poppins } from "next/font/google";

const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-jakarta",
});

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={poppins.className}>
      <body
        className={`${jakarta.variable} ${poppins.variable} antialiased bg-primary`}
        suppressHydrationWarning
      >
        <ThemeProvider>
          <div className="min-h-dvh relative text-primary  cursor-crosshair w-full">
            <ThemeVideo />
            <MobileNav />

            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
